[package]
name = "ncube"
version = "0.1.1"
edition = "2021"
authors = ["Nuno David <email@ndavd.com>"]
license = "MIT"
description = "Generalized hypercube visualizer"

[dependencies]
bevy = "0.11.0"
bevy_egui = "0.21.0"
