[package]
name = "ncube"
version = "0.1.1"
edition = "2021"
authors = ["Nuno David <email@ndavd.com>"]
license = "MIT"
description = "Generalized hypercube visualizer"

[dependencies]
bevy = "0.11.0"
bevy_egui = "0.21.0"
bevy_embedded_assets = "0.8.0"
home = "0.5.5"
serde = "1.0.188"
serde_json = "1.0.105"
